project_id = "oyasxtyvvpvpvlsbncil"

[functions.send-welcome-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.assign-expert]
verify_jwt = false

[functions.send-waitlist-welcome]
verify_jwt = false

[functions.send-waitlist-broadcast]
verify_jwt = false

[functions.send-weekly-newsletter]
verify_jwt = false