project_id = "himthfxaidkwsjfdycet"

[functions.send-welcome-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.assign-expert]
verify_jwt = false

[functions.send-waitlist-welcome]
verify_jwt = false

[functions.send-waitlist-broadcast]
verify_jwt = false

[functions.send-weekly-newsletter]
verify_jwt = false

[functions.scrape-news]
verify_jwt = false

[functions.send-email-campaign]
verify_jwt = false

[functions.scrape-product]
verify_jwt = false